/*
 * Mobile Security Service Server API
 *
 * This is a sample mobile security service server.
 *
 * API version: 1.0.0
 * Contact: dffrench@redhat.com
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package swagger

type Apps struct {
}
