/*
 * Mobile Security Service Server API
 *
 * This is a sample mobile security service server.
 *
 * API version: 1.0.0
 * Contact: dffrench@redhat.com
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package swagger

type AppInitResponse struct {
	Id int64 `json:"id,omitempty"`
	Disabled bool `json:"disabled,omitempty"`
	DisabledMessage string `json:"disabledMessage,omitempty"`
}
