/*
 * Mobile Security Service Server API
 *
 * This is a sample mobile security service server.
 *
 * API version: 1.0.0
 * Contact: dffrench@redhat.com
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package swagger

type AppInit struct {
	Id int64 `json:"id,omitempty"`
	Version string `json:"version,omitempty"`
	DeviceType string `json:"deviceType,omitempty"`
	DeviceVersion string `json:"deviceVersion,omitempty"`
	DeviceId string `json:"deviceId,omitempty"`
}
